### ISSUE TITLE
size mismatch about convnext_large_d_320

### ISSUE THREAD

**Issue by cyy-1234** [dvlab-research/MGM#30]
![gs43MdFlo1](https://github.com/dvlab-research/MiniGemini/assets/59501159/ea3a3524-0554-4daf-8df6-2c1377c78f79)
![image](https://github.com/dvlab-research/MiniGemini/assets/59501159/216b8703-ed7c-4e53-8020-2d32dd6734e0)

Hello, I downloaded the pre-trained model based on the readme and placed it in the corresponding location. Which step did I have a problem with? Please help.

**Comment by yanwei-li** [comment]
Hi, it seems the model is loaded from pre-trained checkpoints, which could be attributed to the image size mismatch (position embedding 577 vs 257). Please make sure the input image size matches the pre-trained models.

**Comment by cyy-1234** [comment]
I just ran "python -m minigemini.serve.cli \
     --model-path work_dirs/Mini-Gemini/Mini-Gemini-13B-HD \
     --image-file <path to your image>", and image-file is a 1024x1024 picture. The above problem occurs without modifying other codes. In addition, what is the path of "model-base", and, Where can I modify the path location of model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup? Looking forward to your reply.

**Comment by yanwei-li** [comment]
Hi, for the error, I guess the downloaded `clip-vit-large-patch14-336` could be the 224 input version model, because the positional embedding setting is a 224 version, please check it.
And the path of `model-base` does not affect the inference here, so you can just ignore it.
For the path of `mm_vision_tower_aux`, you can change it by setting `model.config.mm_vision_tower_aux`, which is by default set to the training loading path saved in `Mini-Gemini-13B-HD/config.json`.
